AllCops:
  Include:
    - Rakefile
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - script/**/*
    - test/**/*
    - vendor/**/*

AbcSize:
  Enabled: false

AmbiguousOperator:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

Encoding:
  EnforcedStyle: when_needed

HandleExceptions:
  Enabled: false

LineLength:
  Max: 120

MethodDefParentheses:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

MethodLength:
  Enabled: false

MultilineBlockChain:
  Enabled: false

TrivialAccessors:
  AllowPredicates: true
